### ISSUE TITLE
Ability to manage a live stream for next release ? 

### ISSUE THREAD

**Issue by endmarsfr** [Purfview/whisper-standalone-win#65] opened 2023-08-25 16:58 UTC
Hi,

First of all I would like to congratulate you on the great job you have done.
I used the latest v145.3 with cuda. it worked fine on several files.
I was wondering if it would be possible to add the ability to manage a live stream in the next version. 

Best regards

**Comment by Purfview** [comment] 2023-08-25 21:50
Dupe of: https://github.com/Purfview/whisper-standalone-win/discussions/27

**Closed by Purfview** 2023-08-25 21:50 UTC

**Comment by endmarsfr** [comment] 2023-08-26 18:04
Hi, 
Excuse me, but I think this is not the same request.
I don't want to transcribe the microphone capture.
I want to do captions on the fly over a video stream.
I think using streamlink to find the audio stream and pass it to faster-whisper will allow that.

best regards

**Comment by Purfview** [comment] 2023-08-26 18:28
For live video stream you need to look for another repo, you'll not find such things here.
