### ISSUE TITLE
I can't run it anymore.

### ISSUE THREAD

**Issue by waritxx** [Purfview/whisper-standalone-win#122] opened 2023-11-26 06:19 UTC
Yesterday It did very good job. But today it has problem.

`H:\Program Files\Whisper-Faster>whisper-faster.exe "E:\Study\Forex\ICT Mentorship\New folder\*.mp4" --language=en --model=medium --batch_recursive

Standalone Faster-Whisper r160.7 running on: CUDA

Batch processing 93 files with wildcard [recursive is ON]: E:\Study\Forex\ICT Mentorship\New folder\*.mp4

Starting transcription on: E:\Study\Forex\ICT Mentorship\New folder\06. February\homework_022117.mp4

Traceback (most recent call last):
  File "D:\whisper-fast\__main__.py", line 790, in <module>
  File "D:\whisper-fast\__main__.py", line 689, in cli
  File "faster_whisper\transcribe.py", line 274, in transcribe
  File "faster_whisper\audio.py", line 52, in decode_audio
  File "faster_whisper\audio.py", line 103, in _resample_frames
  File "faster_whisper\audio.py", line 90, in _group_frames
  File "faster_whisper\audio.py", line 80, in _ignore_invalid_frames
  File "av\container\input.pyx", line 202, in decode
  File "av\container\input.pyx", line 134, in demux
  File "av\container\streams.pyx", line 117, in av.container.streams.StreamContainer.get
IndexError: tuple index out of range
[2540] Failed to execute script '__main__' due to unhandled exception!`

**Comment by Purfview** [comment] 2023-11-26 06:26
Probably "homework_022117.mp4" file is without audio, use `--check_files`.

**Comment by Purfview** [comment] 2023-11-26 06:29
Dupe of [IndexError: tuple index out of range ](https://github.com/Purfview/whisper-standalone-win/issues/111)

**Closed by Purfview** 2023-11-26 06:29 UTC

**Comment by waritxx** [comment] 2023-11-26 06:43
Thanks for replying. I  skip this folder then to another. It works properly.
I will look into from your links.
Thank You !
