### ISSUE TITLE
Large V2 versus Large V3

### ISSUE THREAD

**Issue by EricVee68** [Purfview/whisper-standalone-win#182] opened 2024-01-28 20:51 UTC
Love your executables, excellent work.
An observation that I hope you can elaborate on while running Standalone Faster-Whisper r172.1

When using --model=large-v2, I receive this message:
Warning: Word-level timestamps on translations may not be reliable.

When using --model=large-v3, I receive this message:
Warning: 'large-v3' model may produce inferior results, better use 'large-v2'!

Any updates to either of these, or recommended tweaks for either model (preferably v3)?

Thanks much!

**Comment by Purfview** [comment] 2024-01-28 20:58
> Any updates to either of these, or recommended tweaks for either model (preferably v3)?

What updates? Those are just warnings, use whatever you want.
I feel like "large-v3" needs different defaults on whisper's pseudo-vad settings to hallucinate less.

**Comment by EricVee68** [comment] 2024-01-28 21:09
Got it...
I guess what I'm trying to convey is that YOUR implementation at least offers some "heads up" on what could result in problems.  Especially since most other posts regarding Faster Whisper with model v3 seem to imply it's the best thing since sliced bread! ;-)

**Comment by Purfview** [comment] 2024-01-28 21:21
> Especially since most other posts regarding Faster Whisper with model v3 seem to imply it's the best thing since sliced bread! ;-)

Where did you see such? I've seen only complains that is worse.

Find a single post where it says that it's better: https://github.com/openai/whisper/discussions/1762

And read there: https://deepgram.com/learn/whisper-v3-results

**Comment by Purfview** [comment] 2024-01-28 21:49
Btw, it's dupe of https://github.com/Purfview/whisper-standalone-win/discussions/101

**Closed by Purfview** 2024-01-28 21:49 UTC
