### ISSUE TITLE
Virus total flags

### ISSUE THREAD

**Issue by qayyumabro** [Purfview/whisper-standalone-win#134] opened 2023-12-06 08:13 UTC
This have 4 virus total flags:
https://www.virustotal.com/gui/file/e8f46682f4a21261bf01e4d07b0acf6432cf3272ebbc2a2dc642a1f1441f8fdb

You can contact the antivirus companies to report as false positive through their emails listed here:
https://www.techsupportalert.com/how-to-report-malware-or-false-positives-to-multiple-antivirus-vendors/

**Comment by Purfview** [comment] 2023-12-06 11:31
Dupe of https://github.com/Purfview/whisper-standalone-win/discussions/91

**Closed by Purfview** 2023-12-06 11:31 UTC
