### ISSUE TITLE
RuntimeError: Library cublas64_11.dll is not found or cannot be loaded

### ISSUE THREAD

**Issue by Azrogue** [Purfview/whisper-standalone-win#169] opened 2024-01-07 19:05 UTC
I'm running on Windows 11 with a RTX 3070,
Just started the program with this command :
`whisper-faster.exe "General-20231214_144259-Enregistrement de la réunion.mp3" --language=French --model=medium`

I was getting this error : 
```
Standalone Faster-Whisper r167.3 running on: CUDA


Starting transcription on: General-20231214_144259-Enregistrement de la réunion.mp3

Could not load library cudnn_ops_infer64_8.dll. Error code 126
Please make sure cudnn_ops_infer64_8.dll is in your library path!
```

I've tried to follow [those steps on the NVIDIA website](https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html#installwindows) and now when I restarted the script in a new Terminal i'm getting this error :
```
Starting transcription on: General-20231214_144259-Enregistrement de la réunion.mp3

Traceback (most recent call last):
  File "D:\whisper-fast\__main__.py", line 1100, in <module>
  File "D:\whisper-fast\__main__.py", line 1040, in cli
  File "faster_whisper\transcribe.py", line 1145, in restore_speech_timestamps
  File "faster_whisper\transcribe.py", line 590, in generate_segments
  File "faster_whisper\transcribe.py", line 814, in encode
RuntimeError: Library cublas64_11.dll is not found or cannot be loaded
[8080] Failed to execute script '__main__' due to unhandled exception!
```

I have however a `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.0\bin\cublas64_12.dll` file on my PC so it's maybe that your program don't work with CUDA 12

**Comment by Purfview** [comment] 2024-01-08 00:04
Dupe of https://github.com/Purfview/whisper-standalone-win/issues/43

**Closed by Purfview** 2024-01-08 00:04 UTC
