### ISSUE TITLE
a request: Purfview Whisper Live ?

### ISSUE THREAD

**Issue by lererledd** [Purfview/whisper-standalone-win#240] opened 2024-04-13 07:11 UTC
heeello!! this is not exactly a problem but I do not know where to put it, I'm pretty beginner hahaha, just wanted to know if there is any possibility that you share a version to transcribe live, transcribe the audio system in real time, it would be amazing! there are several systems that already do, but are very complicated and do not match the quality that has purfview, so if you could make some version would save many, thanks! Thank you from the bottom of my heart for everything

**Comment by Purfview** [comment] 2024-04-13 07:16
Dupe of https://github.com/Purfview/whisper-standalone-win/discussions/27

**Closed by Purfview** 2024-04-13 07:16 UTC
